In [1]:
# import numpy
import numpy as np

#1
#finds the distinct/unique common items between these two arrays
#use numpy intersect function to find distinct common items in two arrays

In [37]:
a1 = np.array([1, 2, 3,2, 3, 4, 3, 4, 5, 6])
b1 = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
np.intersect1d(a1,b1)

array([2, 4])

#2
#create a 5x3 array with 1 to 15
#use numpy arange function to get numbers 0 to 14
#use numpy reshape function to get a 3x5 table
#add 1 to each element in the array
#use numpy t function to transpose into a 5x3 table

In [38]:
t2 = (np.arange(15).reshape(3,5)+1).T
print(t2)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


#3
#removes from array aany items that are also present in array b
#use a for loop to check through each element in a
#keep the element in a only if it is not found in b
#substitude the original a with the new a list

In [34]:
a3 = np.array([12, 5, 7, 15, 3, 1, 8])
b3 = np.array([14, 6, 3, 11, 19, 12, 5])
a3 = [i for i in a3 if i not in b3]
a3

[7, 15, 1, 8]

#4
#ride a bicycle from NYC to Key West in 35 days
#see on google map the total distance is 1443 miles
#use numpy random randint function to generate an array ranged 1 to 1443 with 35 numbers
#use numpy sort function to order the array increasingly
#define the last value as 1443
#use numpy random randint function to get 4 days no bicycle
#have these four numbers as index of the record element define them same as the previous element
#use numpy diff function to get an array of the record array
#use numpy append function to add the first day record to the difference array
#print results

In [77]:
mile_record = np.sort(np.random.randint(1,1443,35))
mile_record[34] = 1443
no_date = np.sort(np.random.randint(1,33,4))
mile_record[no_date] = mile_record[no_date-1]
mile_day = np.diff(mile_record)
mile_day = np.append(mile_record[0],mile_day)
print(no_date)
print('total miles by day:')
print(mile_record)
print('miles each day:')
print(mile_day)

[ 1 10 15 29]
total miles by day:
[  11   11   59  106  135  137  265  337  349  365  365  393  399  421
  424  424  649  668  705  711  716  856  924  946  996 1145 1165 1188
 1191 1191 1215 1253 1331 1380 1443]
miles each day:
[ 11   0  48  47  29   2 128  72  12  16   0  28   6  22   3   0 225  19
  37   6   5 140  68  22  50 149  20  23   3   0  24  38  78  49  63]


#5

In [67]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)
nyc_water



C:\Users\jiaqi\Anaconda\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


array([[   1979. , 7102100. ,    1512. ,     213. ],
       [   1980. , 7071639. ,    1506. ,     213. ],
       [   1981. , 7089241. ,    1309. ,     185. ],
       [   1982. , 7109105. ,    1382. ,     194. ],
       [   1983. , 7181224. ,    1424. ,     198. ],
       [   1984. , 7234514. ,    1465. ,     203. ],
       [   1985. , 7274054. ,    1326. ,     182. ],
       [   1986. , 7319246. ,    1351. ,     185. ],
       [   1987. , 7342476. ,    1447. ,     197. ],
       [   1988. , 7353719. ,    1484. ,     202. ],
       [   1989. , 7344175. ,    1402. ,     191. ],
       [   1990. , 7335650. ,    1424. ,     194. ],
       [   1991. , 7374501. ,    1469. ,     199. ],
       [   1992. , 7428944. ,    1369. ,     184. ],
       [   1993. , 7506166. ,    1368.5,     182. ],
       [   1994. , 7570458. ,    1357.7,     179. ],
       [   1995. , 7633040. ,    1325.7,     174. ],
       [   1996. , 7697812. ,    1297.9,     169. ],
       [   1997. , 7773443. ,    1205.5,     1

#What is the maximum yearly NYC consumption of water in millions of gallons per day?
#select the thrid column with comsumption per day data
#use max function to get the max value

In [68]:
nyc_water[:,2].max()

1512.0

#How many calendar years arerepresented within this dataset? 
#use shape function to get number of rows in the data set

In [70]:
nyc_water.shape[0]

39

#What is the mean and the standard deviation of the per capita daily water consumption?
#select the fourth column with daily consumption per capita data
#use mean function to get the mean value
#use std function to get the standar deviation

In [80]:
print('mean:')
print(nyc_water[:,3].mean())
print('standard deviation:')
print(nyc_water[:,3].std())

mean:
160.30769230769232
standard deviation:
31.51894330370624


#What is the increase or decrease in population from year to year? 
#create a new array pop_diff
#select the second column with the population data
#use numpy diff function to get the difference and store into the new array

In [82]:
pop_diff = np.diff(nyc_water[:,1])
pop_diff

array([-30461. ,  17602. ,  19864. ,  72119. ,  53290. ,  39540. ,
        45192. ,  23230. ,  11243. ,  -9544. ,  -8525. ,  38851. ,
        54443. ,  77222. ,  64292. ,  62582. ,  64772. ,  75631. ,
        84816. ,  89401. ,  60618. ,  16685.5,  16685.5,  16685.5,
        16685.5,  16685.5,  16685.5,  16685.5,  16685.5,  16685.5,
        16685.5, 108965. ,  77081. ,  61281. ,  49530. ,  44512. ,
        21171. ,  85025. ])